/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchemasRouteImport } from './routes/schemas'
import { Route as MappingRouteImport } from './routes/mapping'
import { Route as DiffRouteImport } from './routes/diff'
import { Route as IndexRouteImport } from './routes/index'

const SchemasRoute = SchemasRouteImport.update({
  id: '/schemas',
  path: '/schemas',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingRoute = MappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffRoute = DiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diff': typeof DiffRoute
  '/mapping': typeof MappingRoute
  '/schemas': typeof SchemasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diff': typeof DiffRoute
  '/mapping': typeof MappingRoute
  '/schemas': typeof SchemasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diff': typeof DiffRoute
  '/mapping': typeof MappingRoute
  '/schemas': typeof SchemasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diff' | '/mapping' | '/schemas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diff' | '/mapping' | '/schemas'
  id: '__root__' | '/' | '/diff' | '/mapping' | '/schemas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiffRoute: typeof DiffRoute
  MappingRoute: typeof MappingRoute
  SchemasRoute: typeof SchemasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schemas': {
      id: '/schemas'
      path: '/schemas'
      fullPath: '/schemas'
      preLoaderRoute: typeof SchemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapping': {
      id: '/mapping'
      path: '/mapping'
      fullPath: '/mapping'
      preLoaderRoute: typeof MappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff': {
      id: '/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof DiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiffRoute: DiffRoute,
  MappingRoute: MappingRoute,
  SchemasRoute: SchemasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
